version: '3.8'

services:
  defi-security-toolkit:
    build: .
    ports:
      - "8501:8501"
    environment:
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - TENDERLY_API_KEY=${TENDERLY_API_KEY}
      - INFURA_PROJECT_ID=${INFURA_PROJECT_ID}
    volumes:
      - ./contracts:/app/contracts
      - ./slither-reports:/app/slither-reports
      - ./mythril-reports:/app/mythril-reports
      - ./logs:/app/logs