[theme]
base = "dark"
primaryColor = "#00FFAA"                # Neon Green for highlights/buttons
backgroundColor = "#0E1117"             # Very dark background
secondaryBackgroundColor = "#1E1E2E"    # Slight contrast for input sections
textColor = "#F0F0F0"                   # Light text color for better readability
font = "sans serif"                     # Clean modern font

