[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#1c1b1b"

[server]
maxUploadSize = 10
enableCORS = false

[browser]

gatherUsageStats = false this is my code
